language: scala

scala:
- 2.11.7

jdk:
- oraclejdk8

notifications:
  email:
    recipients:
    - vlad@uralian.com

install: /bin/true

script: sbt +clean +test

cache:
  directories:
  - $HOME/.ivy2

env:
  global:
    secure: OcsK5YAuhbsex29F28IlajlpdaieBJ0FTKG/QkZ4qM7J9FoFHXUFjuc7uUN8zxxsLxchtRypggRN6wZVNymGg2NKK5c9WBCR9xaDFFir7pRk4yyFP+miDKQAHsnUjhwqWCFX3hkU5hRVZ7AJV1QjdcOAGcSz7I0fyvXuOOJIlfOu+yQh7TD0izXoYumnrxNpZNpP+oBZlLa732yNuS53wbznU7cyJDlL6/HhqfHUl6aqopy96E9pyjWbSPRjFPkrcBURv1c188D/V5FNbWr8zPngyaWxfsw//MWmbF+wi8tdCRw5SVnsxDobR/GmiicoiGPnpYLLggm2yxII1I3RhGWiNAxBvk8r/whVfCfFJO2rc6cZO8dG1EWzJ5U7J659Owy68LKPcm3KEpfzI6vULAjSwinTinkVEzIqSPvjj1HJaj6T+Bukeeac42ngPDbh0Se65Hpgzo5gkhU1JIPU5lNintdP3jIhNCMSBSvdxXNKIUxWpJNfzSbLqwR9QTBGDIL3vXvdSWfbLBsv+iVCEZjWpIdn7qOeqIrNG923IFUM0bIQnjjb2UJ6x+/x2y/dA9N2bQwYnK3Ptfu1OWY0WTcBXyEbuc4hUWijUs9FzmE6DzJtmyHrQ/ZWXh2FOSGXTmL2w00e7QPp+neVl5qmgU4VMMapxLJi19R55BGcCsg=

before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ci/secring.gpg.enc -out local.secring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ci/pubring.gpg.enc -out local.pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ci/credentials.sbt.enc -out local.credentials.sbt -d

after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt +publishSigned; };'